name: Auto Label Issues

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Apply labels based on issue title/body
        uses: peter-evans/issue-labeler@v3
        with:
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 0
          repo-token: ${{ github.token }}
          issue-number: ${{ github.event.issue.number }}
          functions: ${{ github.event.issue.title }}
          functions: ${{ github.event.issue.body }}